logging:
  config: classpath:logback.xml

---
spring: 
  profiles:
    active: real  
server:    
  port: 8082
---  
  

server:
  port: 3000
  error:
    include-exception : false  
    include-stacktrace: never
    whitelabel:
      enabled: true
  context-path: /
  session:
    cookie:
      http-only: true
    tracking-modes: cookie


spring:
  profiles:
    active: test
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  redis:
    host: localhost
    port: 6379

  jpa:
    database: h2
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate.format_sql: true
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    // data: "classpath:user.sql"

api:
   
  url: 
    signIn: /signIn
    signOut: /signOut
    mypage: /mypage
    accessdenied: /error/accessdenied
    refreshToken: /api/token
  token:
    expired: 60000000
    refreshExpired: 6000000000
    signing-key: securityKey
    
tr:
  path:
    xmlFilePath: /Users/skyrun/git/backend/src/main/resources/jkass/TrxRule
    requestBeanPackage : 
    responseBeanPackage :
    
    